import { TemplateEntity } from '@entities';
import { Module } from '@nestjs/common';
import { NestjsQueryGraphQLModule } from '@nestjs-query/query-graphql';
import { NestjsQueryTypeOrmModule } from '@nestjs-query/query-typeorm';

import { TemplateService } from './template.service';
import { CreateAdminInput, UpdateAdminInput } from './admin.input';
import { TemplateDTO } from './template.dto';

@Module({
  imports: [
    NestjsQueryGraphQLModule.forFeature({
      imports: [NestjsQueryTypeOrmModule.forFeature([TemplateEntity])],
      services: [TemplateService],
      resolvers: [
        {
          ServiceClass: TemplateService,
          DTOClass: TemplateDTO,
          EntityClass: TemplateEntity,
          CreateDTOClass: CreateTemplateInput,
          UpdateDTOClass: UpdateTemplateInput,
          guards: [],
        },
      ],
    }),
  ],
  controllers: [],
})
export class TemplateModule {}
